export const users = [
  {
    user_id: 1,
    username: "admin",
    first_name: "John",
    last_name: "Water",
    email: "jwater0@ucsd.edu",
    password: "admin",
    role: "admin",
  },
  {
    user_id: 2,
    username: "testuser",
    first_name: "Marlin",
    last_name: "Morcombe",
    email: "mmorcombe1@icio.us",
    password: "testuser",
    role: "user",
  },
  {
    user_id: 3,
    username: "pechallier2",
    first_name: "Petra",
    last_name: "Echallier",
    email: "pechallier2@java.com",
    password: "sI4)5o,!wBZ&Qz",
    role: "user",
  },
  {
    user_id: 4,
    username: "dbonds3",
    first_name: "Dredi",
    last_name: "Bonds",
    email: "dbonds3@utexas.edu",
    password: "tJ2fe3M0%n",
    role: "user",
  },
  {
    user_id: 5,
    username: "kdenisovo4",
    first_name: "Kirsteni",
    last_name: "Denisovo",
    email: "kdenisovo4@yale.edu",
    password: 'dM2bIl(Oq"RTu<mo',
    role: "user",
  },
  {
    user_id: 6,
    username: "kjozwiak5",
    first_name: "Karlyn",
    last_name: "Jozwiak",
    email: "kjozwiak5@lycos.com",
    password: "nD32Wy5/$%Q_",
    role: "user",
  },
  {
    user_id: 7,
    username: "idebischof6",
    first_name: "Isaiah",
    last_name: "De Bischof",
    email: "idebischof6@naver.com",
    password: "rV7PMGeOjQiJ!xk",
    role: "user",
  },
  {
    user_id: 8,
    username: "bdenning7",
    first_name: "Barbra",
    last_name: "Denning",
    email: "bdenning7@blogtalkradio.com",
    password: "fF5|6@p~jA6A",
    role: "user",
  },
  {
    user_id: 9,
    username: "mbenedyktowicz8",
    first_name: "Melonie",
    last_name: "Benedyktowicz",
    email: "mbenedyktowicz8@zdnet.com",
    password: "tE4oe*hG{}Q>v",
    role: "user",
  },
  {
    user_id: 10,
    username: "ldiruggiero9",
    first_name: "Letitia",
    last_name: "Di Ruggiero",
    email: "ldiruggiero9@people.com.cn",
    password: "jC8X7t'B8q~",
    role: "user",
  },
  {
    user_id: 11,
    username: "dcawkilla",
    first_name: "Dilly",
    last_name: "Cawkill",
    email: "dcawkilla@uol.com.br",
    password: "wX55.WAQTw*",
    role: "user",
  },
  {
    user_id: 12,
    username: "drozzellb",
    first_name: "Darsie",
    last_name: "Rozzell",
    email: "drozzellb@cmu.edu",
    password: "uK3P?k)6CnS/i1",
    role: "user",
  },
  {
    user_id: 13,
    username: "tworthingc",
    first_name: "Terrance",
    last_name: "Worthing",
    email: "tworthingc@yellowpages.com",
    password: "uS6Qwp_lQQemO",
    role: "user",
  },
  {
    user_id: 14,
    username: "efortund",
    first_name: "Erasmus",
    last_name: "Fortun",
    email: "efortund@linkedin.com",
    password: "jM1zi|k9~EV",
    role: "user",
  },
  {
    user_id: 15,
    username: "fgammone",
    first_name: "Franciskus",
    last_name: "Gammon",
    email: "fgammone@symantec.com",
    password: "sI99%U@h|Y",
    role: "user",
  },
  {
    user_id: 16,
    username: "bheatleyf",
    first_name: "Bertrando",
    last_name: "Heatley",
    email: "bheatleyf@so-net.ne.jp",
    password: "vP8e605|o@Vr*",
    role: "user",
  },
  {
    user_id: 17,
    username: "jmacieiczykg",
    first_name: "Jsandye",
    last_name: "Macieiczyk",
    email: "jmacieiczykg@nifty.com",
    password: "rM70$|tmi3!t",
    role: "user",
  },
  {
    user_id: 18,
    username: "dgergelyh",
    first_name: "Drucill",
    last_name: "Gergely",
    email: "dgergelyh@loc.gov",
    password: "wT4#\\&Rg?m,",
    role: "user",
  },
  {
    user_id: 19,
    username: "mschruursi",
    first_name: "Mala",
    last_name: "Schruurs",
    email: "mschruursi@elegantthemes.com",
    password: "xR6S5qL+jms",
    role: "user",
  },
  {
    user_id: 20,
    username: "dmccomej",
    first_name: "Darill",
    last_name: "McCome",
    email: "dmccomej@thetimes.co.uk",
    password: "cG8CDc3.Ot*A16Z",
    role: "user",
  },
  {
    user_id: 21,
    username: "icleverk",
    first_name: "Inger",
    last_name: "Clever",
    email: "icleverk@hubpages.com",
    password: "mQ3dkZ$`~)*V",
    role: "user",
  },
  {
    user_id: 22,
    username: "dlavensl",
    first_name: "Der",
    last_name: "Lavens",
    email: "dlavensl@google.com.hk",
    password: "yL9fQIBSe<I*Al\\",
    role: "admin",
  },
  {
    user_id: 23,
    username: "nvedyashkinm",
    first_name: "Nevin",
    last_name: "Vedyashkin",
    email: "nvedyashkinm@google.cn",
    password: "uO1%*%ztTdxwokqh",
    role: "user",
  },
  {
    user_id: 24,
    username: "nvindenn",
    first_name: "Nani",
    last_name: "Vinden",
    email: "nvindenn@virginia.edu",
    password: "bD1mQPz+6bvs",
    role: "user",
  },
  {
    user_id: 25,
    username: "cmchaleo",
    first_name: "Cordy",
    last_name: "McHale",
    email: "cmchaleo@wikimedia.org",
    password: "iF7%F&}y.qx0V",
    role: "user",
  },
  {
    user_id: 26,
    username: "nheapsp",
    first_name: "Nester",
    last_name: "Heaps",
    email: "nheapsp@cnn.com",
    password: "qK9@%n(yLm",
    role: "user",
  },
  {
    user_id: 27,
    username: "tdrewsq",
    first_name: "Tim",
    last_name: "Drews",
    email: "tdrewsq@imageshack.us",
    password: "yI8WF!MXDK",
    role: "user",
  },
  {
    user_id: 28,
    username: "rchillingworthr",
    first_name: "Roma",
    last_name: "Chillingworth",
    email: "rchillingworthr@xinhuanet.com",
    password: "aW6>62GCaDu+#f",
    role: "user",
  },
  {
    user_id: 29,
    username: "msimonis",
    first_name: "Morris",
    last_name: "Simoni",
    email: "msimonis@go.com",
    password: "lR7DsWDlT#V*",
    role: "user",
  },
  {
    user_id: 30,
    username: "egiovanit",
    first_name: "Ebenezer",
    last_name: "Giovani",
    email: "egiovanit@last.fm",
    password: "sI8|Mil@xsO",
    role: "user",
  },
  {
    user_id: 31,
    username: "ewillcotu",
    first_name: "Erroll",
    last_name: "Willcot",
    email: "ewillcotu@umich.edu",
    password: "qW4vdUtsV@$4Xg",
    role: "user",
  },
  {
    user_id: 32,
    username: "ldunckleev",
    first_name: "Ludvig",
    last_name: "Duncklee",
    email: "ldunckleev@columbia.edu",
    password: "xW38+6{t0'QbV_Qt",
    role: "user",
  },
  {
    user_id: 33,
    username: "ochessonw",
    first_name: "Orran",
    last_name: "Chesson",
    email: "ochessonw@buzzfeed.com",
    password: "eG0Oa.,/#xH\\",
    role: "user",
  },
  {
    user_id: 34,
    username: "wfraneyx",
    first_name: "Willdon",
    last_name: "Franey",
    email: "wfraneyx@pagesperso-orange.fr",
    password: "iZ0H#BNP5p>w",
    role: "user",
  },
  {
    user_id: 35,
    username: "pwinstoney",
    first_name: "Paxton",
    last_name: "Winstone",
    email: "pwinstoney@mashable.com",
    password: "fV8S3ZHKIj",
    role: "user",
  },
  {
    user_id: 36,
    username: "llappinez",
    first_name: "Laraine",
    last_name: "Lappine",
    email: "llappinez@zdnet.com",
    password: "gP9ilFZ.DWu>8",
    role: "user",
  },
  {
    user_id: 37,
    username: "sfelder10",
    first_name: "Sunny",
    last_name: "Felder",
    email: "sfelder10@nytimes.com",
    password: 'uJ77KGgNQ8">C',
    role: "user",
  },
  {
    user_id: 38,
    username: "cparsonage11",
    first_name: "Cullen",
    last_name: "Parsonage",
    email: "cparsonage11@oakley.com",
    password: "xN5i`kU``qyp}",
    role: "user",
  },
  {
    user_id: 39,
    username: "afonquernie12",
    first_name: "Austin",
    last_name: "Fonquernie",
    email: "afonquernie12@redcross.org",
    password: "mX5alJ=u",
    role: "user",
  },
  {
    user_id: 40,
    username: "dpresho13",
    first_name: "Dorothea",
    last_name: "Presho",
    email: "dpresho13@digg.com",
    password: "qL3hI`a\\",
    role: "user",
  },
  {
    user_id: 41,
    username: "clowten14",
    first_name: "Cicily",
    last_name: "Lowten",
    email: "clowten14@hhs.gov",
    password: "fL3/l9qXpC.Y",
    role: "user",
  },
  {
    user_id: 42,
    username: "rminchell15",
    first_name: "Roland",
    last_name: "Minchell",
    email: "rminchell15@pinterest.com",
    password: "mG8$3|TJ#8",
    role: "user",
  },
  {
    user_id: 43,
    username: "vsantarelli16",
    first_name: "Victoria",
    last_name: "Santarelli",
    email: "vsantarelli16@ebay.com",
    password: "hN0Ag@,%obzm=sp",
    role: "user",
  },
  {
    user_id: 44,
    username: "mmatthius17",
    first_name: "Meriel",
    last_name: "Matthius",
    email: "mmatthius17@instagram.com",
    password: "kL4`MfY$V!",
    role: "user",
  },
  {
    user_id: 45,
    username: "mmarciskewski18",
    first_name: "Malia",
    last_name: "Marciskewski",
    email: "mmarciskewski18@berkeley.edu",
    password: "pN6,?e&c>D6b!lL",
    role: "user",
  },
  {
    user_id: 46,
    username: "cgoldston19",
    first_name: "Carrie",
    last_name: "Goldston",
    email: "cgoldston19@mozilla.org",
    password: "dF0NAs4X0N",
    role: "user",
  },
  {
    user_id: 47,
    username: "hmabbot1a",
    first_name: "Horacio",
    last_name: "Mabbot",
    email: "hmabbot1a@hp.com",
    password: "lW7?U#%D@5OAX",
    role: "user",
  },
  {
    user_id: 48,
    username: "rperillio1b",
    first_name: "Robert",
    last_name: "Perillio",
    email: "rperillio1b@ocn.ne.jp",
    password: 'pF2"1)sFPfX(M',
    role: "user",
  },
  {
    user_id: 49,
    username: "nbagg1c",
    first_name: "Natalie",
    last_name: "Bagg",
    email: "nbagg1c@scribd.com",
    password: "cQ4Old2SnQW2Am*",
    role: "user",
  },
  {
    user_id: 50,
    username: "mmurkin1d",
    first_name: "Marjie",
    last_name: "Murkin",
    email: "mmurkin1d@miitbeian.gov.cn",
    password: "aC0i\\Dc3K",
    role: "user",
  },
];

export default users;